imports 
make sigmoid function
make sigmoid derivation function
learning rate
epochs 

<!-- for loop:
multiply inputs with weights using dot product
y_pred = sigmioid(dot)

calculate error
actual_value - y_pred

delta 
delta = error * sigmoid(y_pred)

update weights

weights+= np.dot(x.t, delta)*lr -->

In [95]:
import numpy as np

In [117]:
def sigmoid(x):
    return 1/(1+np.exp(x))

def sigmoid_der(x):
    return x*(1-x)

lr = 0.1
epochs = 5000

In [118]:
input_array = np.array([[0,0,1], [0,1,1], [1,0,1], [1,1,1]])
output_array = np.array([[0],[0],[0],[1]])

weights = np.random.randn(3)
weights
# weights = np.array([[ 1.62434536],
#        [-0.61175641],
#        [-0.52817175]])

In [114]:
for epoch in range(epochs):
    #prediction
    weighted_inputs = np.dot(input_array, weights)
    y_pred = sigmoid(weighted_inputs)

    #error and delta
    error = output_array - y_pred
    delta = error*sigmoid_der(y_pred)
    print(delta)
    
    #update_weights
    weights+=(np.dot(input_array.T,delta))*lr
    print(y_pred)
    
    
    

[[-0.14678683]
 [-0.13911362]
 [-0.04701803]
 [ 0.14596575]]
[[0.6290566 ]
 [0.75766645]
 [0.25045753]
 [0.38120961]]
[[-0.14707882]
 [-0.13841899]
 [-0.0475365 ]
 [ 0.14579231]]
[[0.63340841]
 [0.76095788]
 [0.25211326]
 [0.38312575]]
[[-0.14733589]
 [-0.13770438]
 [-0.04806442]
 [ 0.14561124]]
[[0.63774525]
 [0.76421433]
 [0.25379481]
 [0.38505643]]
[[-0.14755782]
 [-0.13697068]
 [-0.04860178]
 [ 0.14542252]]
[[0.64206556]
 [0.76743495]
 [0.25550202]
 [0.38700085]]
[[-0.14774447]
 [-0.13621876]
 [-0.04914856]
 [ 0.14522612]]
[[0.64636781]
 [0.77061893]
 [0.25723472]
 [0.38895828]]
[[-0.14789574]
 [-0.13544953]
 [-0.04970473]
 [ 0.14502205]]
[[0.65065053]
 [0.77376557]
 [0.25899276]
 [0.39092801]]
[[-0.14801161]
 [-0.1346639 ]
 [-0.05027028]
 [ 0.1448103 ]]
[[0.65491229]
 [0.7768742 ]
 [0.26077599]
 [0.39290934]]
[[-0.1480921 ]
 [-0.13386278]
 [-0.05084519]
 [ 0.14459088]]
[[0.65915171]
 [0.77994427]
 [0.26258428]
 [0.39490163]]
[[-0.1481373 ]
 [-0.13304707]
 [-0.05142944]
 [ 0.144363

[[0.99796204]
 [0.99912498]
 [0.99810499]
 [0.99918643]]
[[-2.02869436e-03]
 [-8.72991469e-04]
 [-1.88658593e-03]
 [ 6.60368186e-07]]
[[0.99796302]
 [0.99912548]
 [0.99810625]
 [0.99918704]]
[[-2.02772927e-03]
 [-8.72498796e-04]
 [-1.88533448e-03]
 [ 6.59373540e-07]]
[[0.99796399]
 [0.99912597]
 [0.99810751]
 [0.99918765]]
[[-2.02676517e-03]
 [-8.72006679e-04]
 [-1.88408459e-03]
 [ 6.58380977e-07]]
[[0.99796496]
 [0.99912647]
 [0.99810877]
 [0.99918826]]
[[-2.02580208e-03]
 [-8.71515116e-04]
 [-1.88283627e-03]
 [ 6.57390491e-07]]
[[0.99796593]
 [0.99912696]
 [0.99811003]
 [0.99918887]]
[[-2.02483998e-03]
 [-8.71024107e-04]
 [-1.88158951e-03]
 [ 6.56402076e-07]]
[[0.9979669 ]
 [0.99912745]
 [0.99811128]
 [0.99918949]]
[[-2.02387888e-03]
 [-8.70533650e-04]
 [-1.88034430e-03]
 [ 6.55415727e-07]]
[[0.99796787]
 [0.99912795]
 [0.99811254]
 [0.99919009]]
[[-2.02291878e-03]
 [-8.70043746e-04]
 [-1.87910066e-03]
 [ 6.54431439e-07]]
[[0.99796884]
 [0.99912844]
 [0.99811379]
 [0.9991907 ]]
[[-2.

[[-1.04754820e-03]
 [-3.98938544e-04]
 [-7.62897075e-04]
 [ 8.43942250e-08]]
[[0.99895025]
 [0.99960074]
 [0.99923594]
 [0.99970945]]
[[-1.04731752e-03]
 [-3.98834633e-04]
 [-7.62670887e-04]
 [ 8.43373709e-08]]
[[0.99895048]
 [0.99960085]
 [0.99923616]
 [0.99970955]]
[[-1.04708695e-03]
 [-3.98730776e-04]
 [-7.62444825e-04]
 [ 8.42805701e-08]]
[[0.99895071]
 [0.99960095]
 [0.99923639]
 [0.99970965]]
[[-1.04685649e-03]
 [-3.98626971e-04]
 [-7.62218890e-04]
 [ 8.42238226e-08]]
[[0.99895094]
 [0.99960105]
 [0.99923662]
 [0.99970974]]
[[-1.04662613e-03]
 [-3.98523221e-04]
 [-7.61993082e-04]
 [ 8.41671283e-08]]
[[0.99895117]
 [0.99960116]
 [0.99923684]
 [0.99970984]]
[[-1.04639589e-03]
 [-3.98419523e-04]
 [-7.61767400e-04]
 [ 8.41104870e-08]]
[[0.99895141]
 [0.99960126]
 [0.99923707]
 [0.99970994]]
[[-1.04616575e-03]
 [-3.98315879e-04]
 [-7.61541844e-04]
 [ 8.40538988e-08]]
[[0.99895164]
 [0.99960137]
 [0.9992373 ]
 [0.99971004]]
[[-1.04593573e-03]
 [-3.98212288e-04]
 [-7.61316415e-04]
 [ 8.

In [116]:
test_array = np.array([[0,0,1], [0,1,1], [1,0,1], [1,1,1]])
weight_inp = np.dot(test_array,weights)
predicted_array = sigmoid(weight_inp)


print(np.round(predicted_array))


[[1.]
 [1.]
 [1.]
 [1.]]
